version: '2'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
     - 5432:5432
    command: --autovacuum=off --fsync=off --synchronous_commit=off --full_page_writes=off --work_mem=12MB --max-connections=10 --max_wal_senders=0

  rabbitmq:
    image: rabbitmq:3.13.2-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
