name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        uses: ./.github/actions/build

      - name: lint
        run: make lint

  bootstrap:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        uses: ./.github/actions/build

      - name: bootstrap
        run: make bootstrap
