name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: lint
        run: |
          . venv/bin/activate
          make lint

  bootstrap:
    needs: lint
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: secret
        image: postgres:16.2-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s
        ports:
          - 5432:5432

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: bootstrap
        run: |
          . venv/bin/activate
          make bootstrap

        env:
          DATABASE_URL: postgres://postgres:secret@localhost:5432/postgres

      - name: lint the generated project
        run: make lint
        working-directory: testproject

  build-docker-image:
    needs: bootstrap
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: secret
        image: postgres:16.2-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s
        ports:
          - 5432:5432

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: bootstrap
        run: make bootstrap
        env:
          DATABASE_URL: postgres://postgres:secret@localhost:5432/postgres

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: make sure docker image is buildable
        uses: docker/build-push-action@v5
        with:
          build-args: |
            PYTHON_VERSION=${{ env.python-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: testproject
          push: false
