name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build

      - name: lint
        run: make lint

  bootstrap:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        uses: ./.github/actions/build

      - name: bootstrap
        run: make bootstrap

  build-docker-image:
    needs: bootstrap
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        uses: ./.github/actions/build

      - name: bootstrap
        run: make bootstrap

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup buildx
        uses: docker/setup-buildx-action@v2

      - name: make sure docker image is buildable
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PYTHON_VERSION=${{ env.python-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: testproject
          push: false
